### ISSUE TITLE
Cooja not open after adding mobility plugin

### ISSUE THREAD

**Issue by vishal623** [contiki-os/contiki#2609]
Hello,

I have added the mobility plugin after cloning the Contiki repository. I have already made necessary changes in mobility to run it in Contiki. 

I have added the path in cooja and compile the cooja successfully but when I tried to run, it gives me the again the prompt. Please see the below error.

*****@****-Z51-70`:-/contiki/tools/cooja$ sudo ant run
Buildfile: /home/contiki/tools/cooja/build.xml

init:

compile:

copy configs:

jar_cooja:

jar:

init:

compile:

jar:

init:

mspsim:

init:

compile:

jar:

coffee:

init:

compile:
    [javac] Compiling 8 source files to /home/contiki/tools/coffee-manager/build

configs:

jar:
      [jar] Building jar: /home/contiki/tools/coffee-manager/coffee.jar
     [copy] Copying 1 file to /home/contiki/tools/cooja/apps/mspsim/lib

compile:

copy:

jar:

init:

compile:

jar:

init:

clean:
   [delete] Deleting directory /home/contiki/tools/cooja/apps/serial_socket/build

compile:
    [mkdir] Created dir: /home/contiki/tools/cooja/apps/serial_socket/build
    [javac] Compiling 2 source files to /home/contiki/tools/cooja/apps/serial_socket/build

jar:
      [jar] Building jar: /home/contiki/tools/cooja/apps/serial_socket/lib/serial_socket.jar

init:

compile:

jar:

init:

compile:

jar:

init:

clean:
   [delete] Deleting directory /home/contiki/tools/cooja/apps/powertracker/build

compile:
    [mkdir] Created dir: /home/contiki/tools/cooja/apps/powertracker/build
    [javac] Compiling 1 source file to /home/contiki/tools/cooja/apps/powertracker/build

jar:
      [jar] Building jar: /home/contiki/tools/cooja/apps/powertracker/lib/powertracker.jar

run:
     [java]  INFO [AWT-EventQueue-0] (Cooja.java:2856) - External tools default settings: /external_tools_linux_64.config
     [java]  INFO [AWT-EventQueue-0] (Cooja.java:2886) - External tools user settings: /root/.cooja.user.properties
     [java] Exception in thread "AWT-EventQueue-0" java.lang.VerifyError: Bad type on operand stack
     [java] Exception Details:
     [java]   Location:
     [java]     Mobility.<init>(Lorg/contikios/cooja/Simulation;Lorg/contikios/cooja/Cooja;)V @65: invokespecial
     [java]   Reason:
     [java]     Type 'org/contikios/cooja/dialogs/MessageList' (current frame, stack[3]) is not assignable to 'java/awt/Component'
     [java]   Current Frame:
     [java]     bci: @65
     [java]     flags: { }
     [java]     locals: { 'Mobility', 'org/contikios/cooja/Simulation', 'org/contikios/cooja/Cooja' }
     [java]     stack: { 'Mobility', uninitialized 57, uninitialized 57, 'org/contikios/cooja/dialogs/MessageList' }
     [java]   Bytecode:
     [java]     0x0000000: 2a12 072c 03b7 0008 2a04 b500 092a 01b5
     [java]     0x0000010: 000a 2abb 000b 59b7 000c b500 0d2a bb00
     [java]     0x0000020: 0e59 2a09 b700 0fb5 0003 2a2b b500 042a
     [java]     0x0000030: b400 0d01 04b6 0010 2abb 0011 592a b400
     [java]     0x0000040: 0db7 0012 b600 1357 2ab4 000d bb00 1459
     [java]     0x0000050: b700 1512 16b6 0017 2bb6 0018 b600 19b6
     [java]     0x0000060: 001a b600 1bb2 001c bb00 1459 b700 1512
     [java]     0x0000070: 16b6 0017 2bb6 0018 b600 19b6 001a b600
     [java]     0x0000080: 1d2a 1101 f411 00c8 b600 1eb1          
     [java] 
     [java] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
     [java] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
     [java] 	at java.lang.Class.getConstructor0(Class.java:3075)
     [java] 	at java.lang.Class.getConstructor(Class.java:1825)
     [java] 	at org.contikios.cooja.Cooja.registerPlugin(Cooja.java:1930)
     [java] 	at org.contikios.cooja.Cooja.reparseProjectConfig(Cooja.java:1576)
     [java] 	at org.contikios.cooja.Cooja.<init>(Cooja.java:434)
     [java] 	at org.contikios.cooja.Cooja$30.run(Cooja.java:3322)
     [java] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     [java] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [java] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
     [java] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
     [java] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [java] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [java] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [java] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BUILD SUCCESSFUL
Total time: 4 seconds

Why is it happening? It is perfectly wotking in contiki-3.0 source code.

Regards,
Vishal

**Comment by vishal623** [comment]
Now, It gives me the following error: 

check_jar:

init:

compile:
    [javac] /home/contiki/tools/cooja/apps/mobility/build.xml:24: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /home/contiki/tools/cooja/apps/mobility/build
    [javac] /home/contiki/tools/cooja/apps/mobility/java/Mobility.java:70: error: MessageList is abstract; cannot be instantiated
    [javac]   private MessageList log = new MessageList();
    [javac]                             ^
    [javac] /home/contiki/tools/cooja/apps/mobility/java/Mobility.java:76: error: cannot find symbol
    [javac]     log.addPopupMenuItem(null, true); /* Create message list popup */
    [javac]        ^
    [javac]   symbol:   method addPopupMenuItem(<null>,boolean)
    [javac]   location: variable log of type MessageList
    [javac] /home/contiki/tools/cooja/apps/mobility/java/Mobility.java:77: error: incompatible types: MessageList cannot be converted to Component
    [javac]     add(new JScrollPane(log));
    [javac]                         ^
    [javac] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    [javac] 3 errors

BUILD FAILED
/home/contiki/tools/cooja/apps/mobility/build.xml:24: Compile failed; see the compiler error output for details.

Total time: 1 second

This all error comes when I cloned the development version.

**Comment by georgefatsis** [comment]
I suggest to do the following:

Note I assume you have the contiki under the directory /home/user/contiki

```
copy the plugin at the directory: /home/user/contiki/tools/cooja/apps Then navigate inside the directory: cd mobility

Edit build.xml and specificly line 7:

<property name="cooja_jar" value="/home/user/contiki/tools/cooja/dist/cooja.jar"/>

change the directory to the directory your cooja.jar is located

And do the following:

% sudo ant clean

% ant jar

start cooja:

% cd contiki/tools/cooja 
% ant run
create a new simulation file/new simulation
setup the project directories settings/Manage project directories/Enter path manually: ../apps/mobility/ Save as default
quit COOJA
```

**Comment by SELVARAJUshunmugaPriyan** [comment]
For people still interested, when I compiled inside the mobility folder, I got the error: 
`Mobility.java:69: error: MessageList is abstract; cannot be instantiated`

So, I used the concrete class `MessageListUI` in place of the abstract class `MessageList` in Mobility.java file.
