### ISSUE TITLE
Cooja Mote Type

### ISSUE THREAD

**Issue by tomhoward1** [contiki-os/contiki#442]
Hi, im trying to run Cooja with some native mote types to speed up the simulation (I'm currently using the Sky mote type). If I run Cooja, start a new simulation with default parameters, create a Cooja Mote Type with contiki/examples/rime/example-broadcast.c as the source, create some Mote instances, and run the simulation Cooja crashes out with the following.

java.lang.NullPointerException
    at se.sics.cooja.radiomediums.DirectedGraphMedium.analyzeEdges(DirectedGraphMedium.java:217)
    at se.sics.cooja.radiomediums.UDGM$1.analyzeEdges(UDGM.java:119)
    at se.sics.cooja.radiomediums.DirectedGraphMedium.getPotentialDestinations(DirectedGraphMedium.java:234)
    at se.sics.cooja.radiomediums.UDGM.createConnections(UDGM.java:181)
    at se.sics.cooja.radiomediums.AbstractRadioMedium$1.update(AbstractRadioMedium.java:260)
    at java.util.Observable.notifyObservers(Observable.java:159)
    at java.util.Observable.notifyObservers(Observable.java:115)
    at se.sics.cooja.contikimote.interfaces.ContikiRadio.doActionsAfterTick(ContikiRadio.java:351)
    at se.sics.cooja.MoteInterfaceHandler.doActiveActionsAfterTick(MoteInterfaceHandler.java:308)
    at se.sics.cooja.contikimote.ContikiMote.execute(ContikiMote.java:148)
    at se.sics.cooja.motes.AbstractWakeupMote$1.execute(AbstractWakeupMote.java:47)
    at se.sics.cooja.Simulation.run(Simulation.java:280)
    at java.lang.Thread.run(Thread.java:724)

It looks like a problem with the radio simulation, so I selected some of the other medium types but they also crash out. Are there any Cooja Mote Type examples anywhere which work with the radio (blink works but its not useful)?

**Comment by g-oikonomou** [comment]
Where are we on this one chaps? is this still valid?

**Comment by joakimeriksson** [comment]
Probably not - not even an answer here for more than a year so I guess this could be closed?
